PACKAGE_NAME="fake-battery-nut"
PACKAGE_VERSION="1.4.0"
BUILT_MODULE_NAME[0]="fake_battery_nut"
DEST_MODULE_LOCATION[0]="/extra"
AUTOINSTALL="yes"
MAKE[0]="make -C /lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build modules"
